#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O -J $PROXY $1; cd -
}

VERSION=$(gh_releases snipe/snipe-it | grep -v '^v.0' | sort -V | tail -1)
URL="https://github.com/snipe/snipe-it/archive/${VERSION}.tar.gz"
SRC=/usr/local/src

dl $URL $SRC
