#!/bin/bash -e
# regenerate snipe-it secrets and mysql user password

. /etc/default/inithooks

WEBROOT=/var/www/snipe-it
CONF=$WEBROOT/.env

DB_USER=snipeit
DB_PASS=$(mcookie)

sed -i "\|DB_PASSWORD=|s|=.*|=$DB_PASS|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user="$DB_USER" --pass="$DB_PASS"

sed -i "\|API_SECRET=|s|=.*|=$(mcookie)$(mcookie)|" $CONF

php $WEBROOT/artisan config:cache
php $WEBROOT/artisan key:generate --force
php $WEBROOT/artisan config:clear
