#!/bin/bash -e
# set invoice snipe-it admin password & email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

$INITHOOKS_PATH/bin/snipe-it.py --pass="$APP_PASS" --email="$APP_EMAIL"\
    --domain="$APP_DOMAIN"
