[program:snipe-it-worker]
command=/usr/bin/php /var/www/snipe-it/artisan queue:work redis --sleep=3 --tries=3 --no-interaction
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/snipe-it/storage/logs/queue-worker.log
